---
project_name: "don"

gitea_urls:
  api: https://git.xsfx.dev/api/v1/

builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64
      - arm64
      - 386
      - arm

    goarm:
      - 5
      - 6
      - 7

    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/don/cmd/cmds.date={{.Date}}"
      - "-X go.xsfx.dev/don/cmd/cmds.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/don/cmd/cmds.version={{.Version}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^lint:"
      - "^meta:"
      - "^deployment"
      - "happy linting"
      - "prepares release"

archives:
  - format: tar.gz
    replacements:
      darwin: macos

  - format: binary
    id: only-binary
    replacements:
      darwin: macos

release:
  github:
    owner: xsteadfastx
    name: don

brews:
  - name: don
    tap:
      owner: xsteadfastx
      name: homebrew-tap
    commit_author:
      name: Marvin Steadfast
      email: marvin@xsteadfastx.org
    homepage: https://git.xsfx.dev/xsteadfastx/don
    install: |
      bin.install "don"
    test: |
      system "#{bin}/don version"

gomod:
  proxy: true
